---
  - topic_name: /clock
    ros_type_name: rosgraph_msgs/msg/Clock
    gz_type_name: ignition.msgs.Clock
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/cmd_vel
    ros_type_name: geometry_msgs/msg/Twist
    gz_type_name: ignition.msgs.Twist
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/scan
    ros_type_name: sensor_msgs/msg/LaserScan
    gz_type_name: ignition.msgs.LaserScan
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/camera/color/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/camera/color/image_raw
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/camera/depth/camera_info
    ros_type_name: sensor_msgs/msg/CameraInfo
    gz_type_name: ignition.msgs.CameraInfo
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/camera/depth/image_raw
    ros_type_name: sensor_msgs/msg/Image
    gz_type_name: ignition.msgs.Image
    direction: GZ_TO_ROS

  - ros_topic_name: <robot_namespace>/camera/depth/points
    gz_topic_name: <robot_namespace>/camera/depth/image_raw/points
    ros_type_name: sensor_msgs/msg/PointCloud2
    gz_type_name: ignition.msgs.PointCloudPacked
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/range/fl
    ros_type_name: sensor_msgs/msg/LaserScan
    gz_type_name: ignition.msgs.LaserScan
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/range/fr
    ros_type_name: sensor_msgs/msg/LaserScan
    gz_type_name: ignition.msgs.LaserScan
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/range/rl
    ros_type_name: sensor_msgs/msg/LaserScan
    gz_type_name: ignition.msgs.LaserScan
    direction: GZ_TO_ROS

  - topic_name: <robot_namespace>/range/rr
    ros_type_name: sensor_msgs/msg/LaserScan
    gz_type_name: ignition.msgs.LaserScan
    direction: GZ_TO_ROS
