# Quick Start
#
# 1. Run `docker compose -f compose.hardware.yaml up` on the ROSbot
# 2. Open a shell inside a docker container `docker compose -f compose.hardware.yaml exec -it rosbot bash`
# 3. Run `ros2 run teleop_twist_keyboard teleop_twist_keyboard` inside the container

services:
  rosbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_TYPE: hardware
    network_mode: host
    ipc: host
    restart: unless-stopped
    devices:
      - ${SERIAL_PORT:-/dev/ttyUSB0}
      - /dev/bus/usb/ # FTDI
    command: >
      ros2 launch rosbot_bringup bringup.launch.py
        mecanum:=${MECANUM:-False}
        namespace:=${ROBOT_NAMESPACE:-rosbot}
        serial_port:=${SERIAL_PORT:-/dev/ttyUSB0}
