# Quick Start
#
# 1. Run `xhost +local:docker && docker compose -f compose.simulation.yaml up` on the laptop
#    (optionally you can chang `gpu-config` -> `cpu config`).
# 2. Open a shell inside a docker container `docker compose -f compose.simulation.yaml exec -it rosbot bash`
# 3. Run `ros2 run teleop_twist_keyboard teleop_twist_keyboard` inside the container

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}

services:
  rosbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_TYPE: simulation
    network_mode: host
    ipc: host
    <<: [ *gpu-config]
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
        mecanum:=${MECANUM:-False}
        namespace:=${ROBOT_NAMESPACE:-rosbot}
